/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Color;

/**
 *
 * @author Neranji Sulakshika
 */
public class FASTFOOD extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public FASTFOOD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblFASTFOOD = new javax.swing.JLabel();
        btnBurger = new javax.swing.JButton();
        btnSubmarine = new javax.swing.JButton();
        btnHotDog = new javax.swing.JButton();
        btnPizza = new javax.swing.JButton();
        btnSandwitch = new javax.swing.JButton();
        btnDonut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnLKR = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnBurgerPrice = new javax.swing.JLabel();
        btnSubmarinePrice = new javax.swing.JLabel();
        btnHotDogPrice = new javax.swing.JLabel();
        btnPizzaPrice = new javax.swing.JLabel();
        btnSandwitchPrice = new javax.swing.JLabel();
        btnDonutPrice = new javax.swing.JLabel();
        lblTOTAL = new javax.swing.JLabel();
        lblLKRTotal = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        btnCheckout = new javax.swing.JButton();
        lblMyPlate = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        btnMeal = new javax.swing.JButton();
        btnFastfood = new javax.swing.JButton();
        btnAppetizers = new javax.swing.JButton();
        btnBeverages = new javax.swing.JButton();

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 153, 153));
        jLabel20.setText("TOTAL");

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setText("LKR");

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 153, 153));
        jLabel22.setText("0.00");

        jButton7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton7.setText("ADD TO CART");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblFASTFOOD.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblFASTFOOD.setForeground(new java.awt.Color(51, 204, 0));
        lblFASTFOOD.setText("FAST FOOD");

        btnBurger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Burger.jpg"))); // NOI18N
        btnBurger.setText("jButton1");
        btnBurger.setBorder(null);
        btnBurger.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBurger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBurgerMouseClicked(evt);
            }
        });

        btnSubmarine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SUBMARINE.jpg"))); // NOI18N
        btnSubmarine.setText("jButton2");
        btnSubmarine.setBorder(null);
        btnSubmarine.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubmarine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSubmarineMouseClicked(evt);
            }
        });

        btnHotDog.setBackground(new java.awt.Color(51, 51, 51));
        btnHotDog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/HOTDOG.jpg"))); // NOI18N
        btnHotDog.setText("jButton3");
        btnHotDog.setBorder(null);
        btnHotDog.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHotDog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHotDogMouseClicked(evt);
            }
        });

        btnPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PIZA.jpg"))); // NOI18N
        btnPizza.setText("jButton4");
        btnPizza.setBorder(null);
        btnPizza.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPizza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPizzaMouseClicked(evt);
            }
        });
        btnPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPizzaActionPerformed(evt);
            }
        });

        btnSandwitch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SANDWITCH.jpg"))); // NOI18N
        btnSandwitch.setText("jButton5");
        btnSandwitch.setBorder(null);
        btnSandwitch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSandwitch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSandwitchMouseClicked(evt);
            }
        });

        btnDonut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/DONUT.jpg"))); // NOI18N
        btnDonut.setText("jButton6");
        btnDonut.setBorder(null);
        btnDonut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDonut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDonutMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CHEESE BURGER");
        jLabel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("SUBMARINE");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("HOT DOG");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("PIZZA");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("SANDWITCH");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("DONUT");

        btnLKR.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnLKR.setForeground(new java.awt.Color(153, 153, 153));
        btnLKR.setText("LKR");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));
        jLabel9.setText("LKR");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("LKR");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("LKR");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("LKR");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("LKR");

        btnBurgerPrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnBurgerPrice.setForeground(new java.awt.Color(153, 153, 153));
        btnBurgerPrice.setText("200.00");

        btnSubmarinePrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSubmarinePrice.setForeground(new java.awt.Color(153, 153, 153));
        btnSubmarinePrice.setText("200.00");

        btnHotDogPrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnHotDogPrice.setForeground(new java.awt.Color(153, 153, 153));
        btnHotDogPrice.setText("150.00");

        btnPizzaPrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnPizzaPrice.setForeground(new java.awt.Color(153, 153, 153));
        btnPizzaPrice.setText("150.00");

        btnSandwitchPrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSandwitchPrice.setForeground(new java.awt.Color(153, 153, 153));
        btnSandwitchPrice.setText("100.00");

        btnDonutPrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnDonutPrice.setForeground(new java.awt.Color(153, 153, 153));
        btnDonutPrice.setText("60.00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(lblFASTFOOD, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(btnLKR)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBurgerPrice))
                                    .addComponent(btnBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel2)))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnSubmarinePrice)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(212, 212, 212)
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnHotDogPrice))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnSubmarine, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70)
                                        .addComponent(btnHotDog, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(btnSandwitch, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(btnDonut, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addComponent(jLabel5)
                                        .addGap(226, 226, 226)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnPizzaPrice)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSandwitchPrice)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(102, 102, 102))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnDonutPrice)
                                        .addGap(85, 85, 85)))))))
                .addGap(0, 35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(btnHotDog, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFASTFOOD, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSubmarine, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLKR)
                            .addComponent(btnBurgerPrice)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(btnSubmarinePrice)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(btnHotDogPrice))))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSandwitch)
                        .addComponent(btnPizza))
                    .addComponent(btnDonut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(btnPizzaPrice)
                    .addComponent(btnSandwitchPrice)
                    .addComponent(btnDonutPrice))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        lblFASTFOOD.getAccessibleContext().setAccessibleName("lblFASTFOOD");
        btnBurger.getAccessibleContext().setAccessibleName("btnBurger");
        btnSubmarine.getAccessibleContext().setAccessibleName("btnSubmarine");
        btnSubmarine.getAccessibleContext().setAccessibleDescription("");
        btnHotDog.getAccessibleContext().setAccessibleName("btnHotDog");
        btnPizza.getAccessibleContext().setAccessibleName("btnPizza");
        btnSandwitch.getAccessibleContext().setAccessibleName("btnSandwitch");
        btnDonut.getAccessibleContext().setAccessibleName("btnDonut");
        btnLKR.getAccessibleContext().setAccessibleName("btnLKR");
        jLabel9.getAccessibleContext().setAccessibleName("btnLKR");
        jLabel10.getAccessibleContext().setAccessibleName("btnLKR");
        jLabel11.getAccessibleContext().setAccessibleName("btnLKR");
        jLabel12.getAccessibleContext().setAccessibleName("btnLKR");
        jLabel13.getAccessibleContext().setAccessibleName("btnLKR");
        btnBurgerPrice.getAccessibleContext().setAccessibleName("btnBurgerPrice");
        btnSubmarinePrice.getAccessibleContext().setAccessibleName("btnSubmarinePrice");
        btnHotDogPrice.getAccessibleContext().setAccessibleName("btnHotDogPrice");
        btnPizzaPrice.getAccessibleContext().setAccessibleName("btnPizzaPrice");
        btnSandwitchPrice.getAccessibleContext().setAccessibleName("btnSandwitchPrice");
        btnDonutPrice.getAccessibleContext().setAccessibleName("btnDonutPrice");

        lblTOTAL.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTOTAL.setForeground(new java.awt.Color(153, 153, 153));
        lblTOTAL.setText("TOTAL");

        lblLKRTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblLKRTotal.setForeground(new java.awt.Color(153, 153, 153));
        lblLKRTotal.setText("LKR");

        lblTotalPrice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTotalPrice.setForeground(new java.awt.Color(153, 153, 153));
        lblTotalPrice.setText("0.00");

        btnCheckout.setBackground(new java.awt.Color(0, 204, 0));
        btnCheckout.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnCheckout.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckout.setText("CHECKOUT");
        btnCheckout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCheckout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCheckout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCheckoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCheckoutMouseExited(evt);
            }
        });
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });

        lblMyPlate.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        lblMyPlate.setForeground(new java.awt.Color(153, 153, 153));
        lblMyPlate.setText("MY PLATE");

        lblLogo.setForeground(new java.awt.Color(51, 51, 51));
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo.png"))); // NOI18N

        btnMeal.setBackground(new java.awt.Color(0, 204, 0));
        btnMeal.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        btnMeal.setForeground(new java.awt.Color(255, 255, 255));
        btnMeal.setText("MEAL");
        btnMeal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMeal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMeal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMealMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMealMouseExited(evt);
            }
        });
        btnMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMealActionPerformed(evt);
            }
        });

        btnFastfood.setBackground(new java.awt.Color(0, 102, 0));
        btnFastfood.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        btnFastfood.setForeground(new java.awt.Color(255, 255, 255));
        btnFastfood.setText("FAST FOOD");
        btnFastfood.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFastfood.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFastfood.setPreferredSize(new java.awt.Dimension(73, 25));
        btnFastfood.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFastfoodMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFastfoodMouseExited(evt);
            }
        });

        btnAppetizers.setBackground(new java.awt.Color(0, 204, 0));
        btnAppetizers.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        btnAppetizers.setForeground(new java.awt.Color(255, 255, 255));
        btnAppetizers.setText("APPETIZERS");
        btnAppetizers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAppetizers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAppetizers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAppetizersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAppetizersMouseExited(evt);
            }
        });

        btnBeverages.setBackground(new java.awt.Color(0, 204, 0));
        btnBeverages.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        btnBeverages.setForeground(new java.awt.Color(255, 255, 255));
        btnBeverages.setText("BEVERAGES");
        btnBeverages.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBeverages.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBeverages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBeveragesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBeveragesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMeal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFastfood, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAppetizers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBeverages, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lblTOTAL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblLKRTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalPrice))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMyPlate, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFastfood, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAppetizers, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBeverages, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblMyPlate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalPrice)
                            .addComponent(lblLKRTotal)
                            .addComponent(lblTOTAL))
                        .addGap(18, 18, 18)
                        .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );

        lblTOTAL.getAccessibleContext().setAccessibleName("lblTOTAL");
        lblLKRTotal.getAccessibleContext().setAccessibleName("lblLKR");
        lblTotalPrice.getAccessibleContext().setAccessibleName("lblTotalPrice");
        btnCheckout.getAccessibleContext().setAccessibleName("btnCheckout");
        lblMyPlate.getAccessibleContext().setAccessibleName("lblMyPlate");
        lblLogo.getAccessibleContext().setAccessibleName("lblLogo");
        btnMeal.getAccessibleContext().setAccessibleName("btnMeal");
        btnFastfood.getAccessibleContext().setAccessibleName("btnFastfood");
        btnAppetizers.getAccessibleContext().setAccessibleName("btnAppetizers");
        btnBeverages.getAccessibleContext().setAccessibleName("btnBeverages");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPizzaActionPerformed

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckoutActionPerformed

    private void btnMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMealActionPerformed

    private void btnBurgerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBurgerMouseClicked
        BurgerPOPUPMessage bp = new BurgerPOPUPMessage();
        bp.setVisible(true);
    }//GEN-LAST:event_btnBurgerMouseClicked

    private void btnSubmarineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmarineMouseClicked
        SubmarinePOPUPMessage bp = new SubmarinePOPUPMessage();
        bp.setVisible(true);
    }//GEN-LAST:event_btnSubmarineMouseClicked

    private void btnHotDogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHotDogMouseClicked
        HotDogPOPUPMessage bp = new HotDogPOPUPMessage();
        bp.setVisible(true);
    }//GEN-LAST:event_btnHotDogMouseClicked

    private void btnPizzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPizzaMouseClicked
        PizzaPOPUPMessage bp = new PizzaPOPUPMessage();
        bp.setVisible(true);
    }//GEN-LAST:event_btnPizzaMouseClicked

    private void btnSandwitchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSandwitchMouseClicked
        SandwitchPOPUPMessage bp = new SandwitchPOPUPMessage();
        bp.setVisible(true);
    }//GEN-LAST:event_btnSandwitchMouseClicked

    private void btnDonutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDonutMouseClicked
        DonutPOPUPMessage bp = new DonutPOPUPMessage();
        bp.setVisible(true);
    }//GEN-LAST:event_btnDonutMouseClicked

    private void btnMealMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMealMouseEntered
        btnMeal.setBackground(new Color(0,102,0));
        btnFastfood.setBackground(Color.yellow);
        btnFastfood.setForeground(Color.BLACK);        
    }//GEN-LAST:event_btnMealMouseEntered

    private void btnMealMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMealMouseExited
        btnMeal.setBackground(Color.GREEN);
        btnFastfood.setBackground(new Color(0,102,0));
        btnFastfood.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnMealMouseExited

    private void btnFastfoodMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFastfoodMouseEntered
        btnFastfood.setBackground(Color.yellow);
        btnFastfood.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnFastfoodMouseEntered

    private void btnFastfoodMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFastfoodMouseExited
        btnFastfood.setBackground(new Color(0,102,0));
        btnFastfood.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnFastfoodMouseExited

    private void btnAppetizersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppetizersMouseEntered
        btnAppetizers.setBackground(new Color(0,102,0));
        btnFastfood.setBackground(Color.yellow);
        btnFastfood.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnAppetizersMouseEntered

    private void btnAppetizersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppetizersMouseExited
        btnAppetizers.setBackground(Color.GREEN);
        btnFastfood.setBackground(new Color(0,102,0));
        btnFastfood.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnAppetizersMouseExited

    private void btnBeveragesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBeveragesMouseEntered
        btnBeverages.setBackground(new Color(0,102,0));
        btnFastfood.setBackground(Color.yellow);
        btnFastfood.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnBeveragesMouseEntered

    private void btnBeveragesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBeveragesMouseExited
        btnBeverages.setBackground(Color.GREEN);
        btnFastfood.setBackground(new Color(0,102,0));
        btnFastfood.setForeground(Color.WHITE);
    }//GEN-LAST:event_btnBeveragesMouseExited

    private void btnCheckoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckoutMouseEntered
        btnCheckout.setBackground(Color.RED);
    }//GEN-LAST:event_btnCheckoutMouseEntered

    private void btnCheckoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCheckoutMouseExited
        btnCheckout.setBackground(Color.GREEN);
    }//GEN-LAST:event_btnCheckoutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FASTFOOD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FASTFOOD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FASTFOOD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FASTFOOD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FASTFOOD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppetizers;
    private javax.swing.JButton btnBeverages;
    private javax.swing.JButton btnBurger;
    private javax.swing.JLabel btnBurgerPrice;
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnDonut;
    private javax.swing.JLabel btnDonutPrice;
    private javax.swing.JButton btnFastfood;
    private javax.swing.JButton btnHotDog;
    private javax.swing.JLabel btnHotDogPrice;
    private javax.swing.JLabel btnLKR;
    private javax.swing.JButton btnMeal;
    private javax.swing.JButton btnPizza;
    private javax.swing.JLabel btnPizzaPrice;
    private javax.swing.JButton btnSandwitch;
    private javax.swing.JLabel btnSandwitchPrice;
    private javax.swing.JButton btnSubmarine;
    private javax.swing.JLabel btnSubmarinePrice;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblFASTFOOD;
    private javax.swing.JLabel lblLKRTotal;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMyPlate;
    private javax.swing.JLabel lblTOTAL;
    private javax.swing.JLabel lblTotalPrice;
    // End of variables declaration//GEN-END:variables
}
