/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Color;

/**
 *
 * @author Neranji Sulakshika
 */
public class PizzaPOPUPMessage extends javax.swing.JFrame {

    /**
     * Creates new form PizzaPOPUPMessage
     */
    public PizzaPOPUPMessage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPizza = new javax.swing.JLabel();
        lblPizzaName = new javax.swing.JLabel();
        lblPizzaPrice = new javax.swing.JLabel();
        lblLKR = new javax.swing.JLabel();
        lblQTY = new javax.swing.JLabel();
        spQtyPizza = new javax.swing.JSpinner();
        lblTotal = new javax.swing.JLabel();
        lblTotalLKR = new javax.swing.JLabel();
        btnAddToPlatePizza = new javax.swing.JButton();
        lblPizzaTotalPrice = new javax.swing.JLabel();
        lblCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 530));
        jPanel1.setLayout(null);

        lblPizza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PIZA.jpg"))); // NOI18N
        jPanel1.add(lblPizza);
        lblPizza.setBounds(70, 40, 250, 170);
        lblPizza.getAccessibleContext().setAccessibleName("lblPizza");

        lblPizzaName.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblPizzaName.setForeground(new java.awt.Color(0, 0, 0));
        lblPizzaName.setText("PIZZA");
        jPanel1.add(lblPizzaName);
        lblPizzaName.setBounds(150, 220, 120, 30);
        lblPizzaName.getAccessibleContext().setAccessibleName("lblPizzaName");

        lblPizzaPrice.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lblPizzaPrice.setForeground(new java.awt.Color(51, 51, 51));
        lblPizzaPrice.setText("150.00");
        jPanel1.add(lblPizzaPrice);
        lblPizzaPrice.setBounds(180, 260, 50, 20);
        lblPizzaPrice.getAccessibleContext().setAccessibleName("lblPizzaPrice");

        lblLKR.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lblLKR.setForeground(new java.awt.Color(51, 51, 51));
        lblLKR.setText("LKR");
        lblLKR.setInheritsPopupMenu(false);
        jPanel1.add(lblLKR);
        lblLKR.setBounds(140, 260, 40, 20);
        lblLKR.getAccessibleContext().setAccessibleName("lblLKR");

        lblQTY.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblQTY.setForeground(new java.awt.Color(0, 0, 0));
        lblQTY.setText("QTY");
        jPanel1.add(lblQTY);
        lblQTY.setBounds(60, 330, 50, 30);
        lblQTY.getAccessibleContext().setAccessibleName("lblQTY");

        spQtyPizza.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        spQtyPizza.setBorder(null);
        spQtyPizza.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(spQtyPizza);
        spQtyPizza.setBounds(110, 320, 50, 50);
        spQtyPizza.getAccessibleContext().setAccessibleName("spQtyPizza");

        lblTotal.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(102, 102, 102));
        lblTotal.setText("TOTAL :");
        jPanel1.add(lblTotal);
        lblTotal.setBounds(200, 330, 60, 30);
        lblTotal.getAccessibleContext().setAccessibleName("lblTotal");

        lblTotalLKR.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lblTotalLKR.setForeground(new java.awt.Color(51, 51, 51));
        lblTotalLKR.setText("LKR");
        jPanel1.add(lblTotalLKR);
        lblTotalLKR.setBounds(280, 330, 40, 30);
        lblTotalLKR.getAccessibleContext().setAccessibleName("lblTotalLKR");

        btnAddToPlatePizza.setBackground(new java.awt.Color(0, 153, 0));
        btnAddToPlatePizza.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnAddToPlatePizza.setForeground(new java.awt.Color(255, 255, 255));
        btnAddToPlatePizza.setText("ADD TO PLATE");
        btnAddToPlatePizza.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddToPlatePizza.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddToPlatePizza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddToPlatePizzaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddToPlatePizzaMouseExited(evt);
            }
        });
        jPanel1.add(btnAddToPlatePizza);
        btnAddToPlatePizza.setBounds(100, 410, 210, 60);
        btnAddToPlatePizza.getAccessibleContext().setAccessibleName("btnAddToPlatePizza");

        lblPizzaTotalPrice.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lblPizzaTotalPrice.setForeground(new java.awt.Color(51, 51, 51));
        lblPizzaTotalPrice.setText("150.00");
        jPanel1.add(lblPizzaTotalPrice);
        lblPizzaTotalPrice.setBounds(320, 330, 50, 30);
        lblPizzaTotalPrice.getAccessibleContext().setAccessibleName("lblPizzaTotalPrice");

        lblCancel.setBackground(new java.awt.Color(255, 0, 0));
        lblCancel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblCancel.setForeground(new java.awt.Color(255, 255, 255));
        lblCancel.setText("X");
        lblCancel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        lblCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCancel.setPreferredSize(new java.awt.Dimension(181, 36));
        lblCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCancelMouseClicked(evt);
            }
        });
        lblCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblCancelActionPerformed(evt);
            }
        });
        jPanel1.add(lblCancel);
        lblCancel.setBounds(370, 10, 20, 20);
        lblCancel.getAccessibleContext().setAccessibleName("lblCancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(400, 530));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCancelMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_lblCancelMouseClicked

    private void lblCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCancelActionPerformed

    private void btnAddToPlatePizzaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddToPlatePizzaMouseEntered
        btnAddToPlatePizza.setBackground(Color.RED);
    }//GEN-LAST:event_btnAddToPlatePizzaMouseEntered

    private void btnAddToPlatePizzaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddToPlatePizzaMouseExited
        btnAddToPlatePizza.setBackground(Color.GREEN);
    }//GEN-LAST:event_btnAddToPlatePizzaMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PizzaPOPUPMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PizzaPOPUPMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PizzaPOPUPMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PizzaPOPUPMessage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PizzaPOPUPMessage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToPlatePizza;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lblCancel;
    private javax.swing.JLabel lblLKR;
    private javax.swing.JLabel lblPizza;
    private javax.swing.JLabel lblPizzaName;
    private javax.swing.JLabel lblPizzaPrice;
    private javax.swing.JLabel lblPizzaTotalPrice;
    private javax.swing.JLabel lblQTY;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalLKR;
    private javax.swing.JSpinner spQtyPizza;
    // End of variables declaration//GEN-END:variables
}
